services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/var/www/html/index.html

  certbot:
    build:
      context: .
      dockerfile: Dockerfile 
    volumes:
      - ./certbot-config:/etc/letsencrypt
    entrypoint: /bin/sh
    command: -c 'certbot certonly --dns-ovh --dns-ovh-credentials /etc/letsencrypt/ovh.credentials -d team-croquette.site -d adminer.team-croquette.site --email admin@localhost.com --agree-tos --non-interactive --force-renewal'
    depends_on:
      - nginx

  db: 
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  pg-data:
  certbot-config:
