services:
  nginx:
    image: nginx:latest
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/var/www/html/index.html

  db: 
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  pg-data:
