services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/var/www/html/index.html
      - ./certbot-config:/etc/letsencrypt
      - ./nginx/logs:/nginx/logs

  certbot:
    container_name: certbot
    build:
      context: .
      dockerfile: Dockerfile 
    volumes:
      - ./certbot-config:/etc/letsencrypt
    entrypoint: /bin/sh
    command: -c 'certbot certonly --dns-ovh --dns-ovh-credentials /etc/letsencrypt/ovh.credentials -d team-croquette.site -d adminer.team-croquette.site --email admin@localhost.com --agree-tos --non-interactive --force-renewal'
    depends_on:
      - nginx

  db: 
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

  fail2ban:
    container_name: fail2ban
    image: lscr.io/linuxserver/fail2ban:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./:/config
      - ./nginx/logs:/nginx/logs

volumes:
  pg-data:
  certbot-config:
